#pragma once
#import <AppKit/AppKit.h>
#include <functional>
#include <memory>
#include <vector>

// Tag our own events so InputMethodKit does not interpret them as new input.
static constexpr int64_t MSIMEVoiceCommitEventTag = 0x4d53494d45564f49LL;
enum class MSIMEVoiceCommitOutcome { unavailable, posted, stale };

static inline NSString *MSIMEVoiceCommitMode(id value) {
    return [value isKindOfClass:NSString.class] &&
        [@[@"sendinput", @"ctrl_v"] containsObject:value] ? [value copy] : @"tsf";
}

struct MSIMEVoiceCommitIO {
    std::function<bool()> permitted = [] { return CGPreflightPostEventAccess(); };
    std::function<CGEventRef(CGKeyCode, bool)> create = [](CGKeyCode key, bool down) {
        return CGEventCreateKeyboardEvent(nullptr, key, down);
    };
    std::function<void(pid_t, CGEventRef)> post = [](pid_t pid, CGEventRef event) { CGEventPostToPid(pid, event); };
    std::function<bool(NSString *)> clipboard = [](NSString *text) {
        NSPasteboardItem *item = [NSPasteboardItem new];
        // Clipboard history must not retain recognized text, including our own capture service.
        if (![item setString:text forType:NSPasteboardTypeString] ||
            ![item setData:NSData.data forType:@"org.nspasteboard.ConcealedType"] ||
            ![item setData:NSData.data forType:@"org.nspasteboard.AutoGeneratedType"]) return false;
        NSPasteboard *pasteboard = NSPasteboard.generalPasteboard;
        [pasteboard clearContents];
        return bool([pasteboard writeObjects:@[item]]);
    };
};

struct MSIMEVoiceCommitRoute {
    static constexpr NSUInteger kEventChunkUnits = 16;
    NSString *mode = @"tsf";
    pid_t pid = 0;
    std::function<bool()> current;

    MSIMEVoiceCommitOutcome deliver(NSString *text, const MSIMEVoiceCommitIO &io = {}) const {
        if ([mode isEqual:@"tsf"] || ![text isKindOfClass:NSString.class] ||
            !text.length || text.length > 65536 || pid <= 0 || !current)
            return MSIMEVoiceCommitOutcome::unavailable;
        if (!current()) return MSIMEVoiceCommitOutcome::stale;
        if (!io.permitted()) return MSIMEVoiceCommitOutcome::unavailable;
        using Event = std::unique_ptr<__CGEvent, decltype(&CFRelease)>;
        const bool paste = [mode isEqual:@"ctrl_v"];
        std::vector<Event> events;
        const NSUInteger chunks = (text.length + kEventChunkUnits - 1) / kEventChunkUnits;
        events.reserve(paste ? 2 : chunks * 2);
        for (NSUInteger offset = 0; offset < text.length;) {
            NSUInteger count = MIN(kEventChunkUnits, text.length - offset);
            if (offset + count < text.length && CFStringIsSurrogateHighCharacter([text characterAtIndex:offset + count - 1])) --count;
            UniChar units[kEventChunkUnits]; [text getCharacters:units range:NSMakeRange(offset, count)];
            for (bool down : {true, false}) {
                Event event(io.create(paste ? 9 : 0, down), CFRelease);
                if (!event) return MSIMEVoiceCommitOutcome::unavailable;
                CGEventSetFlags(event.get(), paste ? kCGEventFlagMaskCommand : 0);
                CGEventSetIntegerValueField(event.get(), kCGEventSourceUserData, MSIMEVoiceCommitEventTag);
                if (!paste) CGEventKeyboardSetUnicodeString(event.get(), count, units);
                events.push_back(std::move(event));
            }
            if (paste) break;
            offset += count;
        }
        if (!current()) return MSIMEVoiceCommitOutcome::stale;
        if (paste && !io.clipboard(text)) return MSIMEVoiceCommitOutcome::unavailable;
        for (size_t i = 0; i < events.size(); i += 2) {
            // A partial delivery cannot fall back to IMK without duplicating text.
            if (!current()) return i ? MSIMEVoiceCommitOutcome::posted : MSIMEVoiceCommitOutcome::stale;
            io.post(pid, events[i].get());
            io.post(pid, events[i + 1].get());
        }
        return MSIMEVoiceCommitOutcome::posted;
    }
};

static inline MSIMEVoiceCommitRoute MSIMECaptureVoiceCommit(id mode, id client) {
    MSIMEVoiceCommitRoute route;
    route.mode = MSIMEVoiceCommitMode(mode);
    if ([route.mode isEqual:@"tsf"] || ![client respondsToSelector:@selector(bundleIdentifier)]) return route;
    NSString *bundle = [[client bundleIdentifier] copy];
    NSRunningApplication *application = NSWorkspace.sharedWorkspace.frontmostApplication;
    if (!bundle.length || ![application.bundleIdentifier isEqual:bundle] ||
        application.processIdentifier == NSProcessInfo.processInfo.processIdentifier) return route;
    route.pid = application.processIdentifier;
    route.current = [application, bundle] {
        NSRunningApplication *front = NSWorkspace.sharedWorkspace.frontmostApplication;
        return !application.terminated && front.processIdentifier == application.processIdentifier &&
            [front.bundleIdentifier isEqual:bundle];
    };
    return route;
}
