#ifndef Edition
#define Edition "full"
#endif
#define MyDataDirMarkerPrefix ".metasequoiaime-data"
#if Edition == "full"
#define MyEditionIsFull 1
#define MyEditionAppName "Metasequoia IME 水杉输入法"
#define MyEditionAppId "{{A7C3E91F-4B2D-4E8A-9F1C-6D5E8B0A2C4D}"
#define MyEditionClsid "{E3062E9A-D834-4637-8958-ED8CFA427D01}"
#define MyEditionInstallDir "metasequoiaime"
#define MyEditionRegistryKey "Software\Metasequoia\MetasequoiaIME"
#define MyEditionWatchdogTask "Metasequoia IME Watchdog"
#define MyEditionInstallerBaseName "MetasequoiaIME_Setup"
#define MyEditionDataDirMarker ".metasequoiaime-data"
#define MyOtherEditionRegistryKeys "Software\Metasequoia\MetasequoiaIME-Pinyin|Software\Metasequoia\MetasequoiaIME-Wubi|Software\Metasequoia\MetasequoiaIME-Japanese|Software\Metasequoia\MetasequoiaIME-Vietnamese|Software\Metasequoia\MetasequoiaIME-Tibetan"
#define MyOtherEditionInstallDirs "metasequoiaime-pinyin|metasequoiaime-wubi|metasequoiaime-japanese|metasequoiaime-vietnamese|metasequoiaime-tibetan"
#elif Edition == "pinyin"
#define MyEditionIsFull 0
#define MyEditionAppName "Metasequoia IME 水杉拼音"
#define MyEditionAppId "{{EB4125FA-5687-4698-9E43-2C4CA4652132}"
#define MyEditionClsid "{7C927972-6D06-44C7-9B7C-B0D00C77D7C7}"
#define MyEditionInstallDir "metasequoiaime-pinyin"
#define MyEditionRegistryKey "Software\Metasequoia\MetasequoiaIME-Pinyin"
#define MyEditionWatchdogTask "Metasequoia IME Watchdog (Pinyin)"
#define MyEditionInstallerBaseName "MetasequoiaIME-Pinyin_Setup"
#define MyEditionDataDirMarker ".metasequoiaime-data.pinyin"
#define MyOtherEditionRegistryKeys "Software\Metasequoia\MetasequoiaIME|Software\Metasequoia\MetasequoiaIME-Wubi|Software\Metasequoia\MetasequoiaIME-Japanese|Software\Metasequoia\MetasequoiaIME-Vietnamese|Software\Metasequoia\MetasequoiaIME-Tibetan"
#define MyOtherEditionInstallDirs "metasequoiaime|metasequoiaime-wubi|metasequoiaime-japanese|metasequoiaime-vietnamese|metasequoiaime-tibetan"
#elif Edition == "wubi"
#define MyEditionIsFull 0
#define MyEditionAppName "Metasequoia IME 水杉五笔"
#define MyEditionAppId "{{FF5943BF-0F4B-4999-8504-15235E4516C6}"
#define MyEditionClsid "{FD41CA20-BA49-41FE-96BE-923DCCA191DA}"
#define MyEditionInstallDir "metasequoiaime-wubi"
#define MyEditionRegistryKey "Software\Metasequoia\MetasequoiaIME-Wubi"
#define MyEditionWatchdogTask "Metasequoia IME Watchdog (Wubi)"
#define MyEditionInstallerBaseName "MetasequoiaIME-Wubi_Setup"
#define MyEditionDataDirMarker ".metasequoiaime-data.wubi"
#define MyOtherEditionRegistryKeys "Software\Metasequoia\MetasequoiaIME|Software\Metasequoia\MetasequoiaIME-Pinyin|Software\Metasequoia\MetasequoiaIME-Japanese|Software\Metasequoia\MetasequoiaIME-Vietnamese|Software\Metasequoia\MetasequoiaIME-Tibetan"
#define MyOtherEditionInstallDirs "metasequoiaime|metasequoiaime-pinyin|metasequoiaime-japanese|metasequoiaime-vietnamese|metasequoiaime-tibetan"
#elif Edition == "japanese"
#define MyEditionIsFull 0
#define MyEditionAppName "Metasequoia IME 水杉日语"
#define MyEditionAppId "{{41454B5E-8298-42B8-BA6F-5DD2FE559E5E}"
#define MyEditionClsid "{43218C33-7729-47CC-A485-5F43B77F696A}"
#define MyEditionInstallDir "metasequoiaime-japanese"
#define MyEditionRegistryKey "Software\Metasequoia\MetasequoiaIME-Japanese"
#define MyEditionWatchdogTask "Metasequoia IME Watchdog (Japanese)"
#define MyEditionInstallerBaseName "MetasequoiaIME-Japanese_Setup"
#define MyEditionDataDirMarker ".metasequoiaime-data.japanese"
#define MyOtherEditionRegistryKeys "Software\Metasequoia\MetasequoiaIME|Software\Metasequoia\MetasequoiaIME-Pinyin|Software\Metasequoia\MetasequoiaIME-Wubi|Software\Metasequoia\MetasequoiaIME-Vietnamese|Software\Metasequoia\MetasequoiaIME-Tibetan"
#define MyOtherEditionInstallDirs "metasequoiaime|metasequoiaime-pinyin|metasequoiaime-wubi|metasequoiaime-vietnamese|metasequoiaime-tibetan"
#elif Edition == "vietnamese"
#define MyEditionIsFull 0
#define MyEditionAppName "Metasequoia IME 水杉越南语"
#define MyEditionAppId "{{BA5F9864-3095-469D-BCB5-B0562EB51263}"
#define MyEditionClsid "{0CFED878-B045-4604-8DED-845A7C80CABE}"
#define MyEditionInstallDir "metasequoiaime-vietnamese"
#define MyEditionRegistryKey "Software\Metasequoia\MetasequoiaIME-Vietnamese"
#define MyEditionWatchdogTask "Metasequoia IME Watchdog (Vietnamese)"
#define MyEditionInstallerBaseName "MetasequoiaIME-Vietnamese_Setup"
#define MyEditionDataDirMarker ".metasequoiaime-data.vietnamese"
#define MyOtherEditionRegistryKeys "Software\Metasequoia\MetasequoiaIME|Software\Metasequoia\MetasequoiaIME-Pinyin|Software\Metasequoia\MetasequoiaIME-Wubi|Software\Metasequoia\MetasequoiaIME-Japanese|Software\Metasequoia\MetasequoiaIME-Tibetan"
#define MyOtherEditionInstallDirs "metasequoiaime|metasequoiaime-pinyin|metasequoiaime-wubi|metasequoiaime-japanese|metasequoiaime-tibetan"
#elif Edition == "tibetan"
#define MyEditionIsFull 0
#define MyEditionAppName "Metasequoia IME 水杉藏文"
#define MyEditionAppId "{{68802231-3EDF-4B67-B80F-DFB95A1BAD01}"
#define MyEditionClsid "{93DEEE80-9145-4257-BF11-957FDFE0A75E}"
#define MyEditionInstallDir "metasequoiaime-tibetan"
#define MyEditionRegistryKey "Software\Metasequoia\MetasequoiaIME-Tibetan"
#define MyEditionWatchdogTask "Metasequoia IME Watchdog (Tibetan)"
#define MyEditionInstallerBaseName "MetasequoiaIME-Tibetan_Setup"
#define MyEditionDataDirMarker ".metasequoiaime-data.tibetan"
#define MyOtherEditionRegistryKeys "Software\Metasequoia\MetasequoiaIME|Software\Metasequoia\MetasequoiaIME-Pinyin|Software\Metasequoia\MetasequoiaIME-Wubi|Software\Metasequoia\MetasequoiaIME-Japanese|Software\Metasequoia\MetasequoiaIME-Vietnamese"
#define MyOtherEditionInstallDirs "metasequoiaime|metasequoiaime-pinyin|metasequoiaime-wubi|metasequoiaime-japanese|metasequoiaime-vietnamese"
#else
#error Unknown edition; use /DEdition= one of full, pinyin, wubi, japanese, vietnamese, tibetan
#endif
