#ifndef Edition
#define Edition "full"
#endif
#define MyDataDirMarkerPrefix ".metasequoiaime-data"
#if Edition == "full"
#define MyEditionAppName "水杉输入法"
#define MyEditionAppId "{{4391158B-18CF-4B7A-A924-7FBBC23FB3F8}"
#define MyEditionClsid "{A1160FE1-DE82-4216-9F2A-BC8A8A76F8B9}"
#define MyEditionInstallDir "metasequoiaime-full"
#define MyEditionRegistryKey "Software\Metasequoia\MetasequoiaIME-Full"
#define MyEditionWatchdogTask "Metasequoia IME Watchdog (Full)"
#define MyEditionInstallerBaseName "MetasequoiaIME-Full_Setup"
#define MyEditionDataDirMarker ".metasequoiaime-data.full"
#define MyOtherEditionRegistryKeys "Software\Metasequoia\MetasequoiaIME-Pinyin|Software\Metasequoia\MetasequoiaIME-Wubi|Software\Metasequoia\MetasequoiaIME-Japanese|Software\Metasequoia\MetasequoiaIME-Vietnamese|Software\Metasequoia\MetasequoiaIME-Tibetan|Software\Metasequoia\MetasequoiaIME"
#define MyOtherEditionInstallDirs "metasequoiaime-pinyin|metasequoiaime-wubi|metasequoiaime-japanese|metasequoiaime-vietnamese|metasequoiaime-tibetan|metasequoiaime"
#elif Edition == "pinyin"
#define MyEditionAppName "Metasequoia IME 水杉拼音"
#define MyEditionAppId "{{EB4125FA-5687-4698-9E43-2C4CA4652132}"
#define MyEditionClsid "{7C927972-6D06-44C7-9B7C-B0D00C77D7C7}"
#define MyEditionInstallDir "metasequoiaime-pinyin"
#define MyEditionRegistryKey "Software\Metasequoia\MetasequoiaIME-Pinyin"
#define MyEditionWatchdogTask "Metasequoia IME Watchdog (Pinyin)"
#define MyEditionInstallerBaseName "MetasequoiaIME-Pinyin_Setup"
#define MyEditionDataDirMarker ".metasequoiaime-data.pinyin"
#define MyOtherEditionRegistryKeys "Software\Metasequoia\MetasequoiaIME-Full|Software\Metasequoia\MetasequoiaIME-Wubi|Software\Metasequoia\MetasequoiaIME-Japanese|Software\Metasequoia\MetasequoiaIME-Vietnamese|Software\Metasequoia\MetasequoiaIME-Tibetan|Software\Metasequoia\MetasequoiaIME"
#define MyOtherEditionInstallDirs "metasequoiaime-full|metasequoiaime-wubi|metasequoiaime-japanese|metasequoiaime-vietnamese|metasequoiaime-tibetan|metasequoiaime"
#elif Edition == "wubi"
#define MyEditionAppName "Metasequoia IME 水杉五笔"
#define MyEditionAppId "{{FF5943BF-0F4B-4999-8504-15235E4516C6}"
#define MyEditionClsid "{FD41CA20-BA49-41FE-96BE-923DCCA191DA}"
#define MyEditionInstallDir "metasequoiaime-wubi"
#define MyEditionRegistryKey "Software\Metasequoia\MetasequoiaIME-Wubi"
#define MyEditionWatchdogTask "Metasequoia IME Watchdog (Wubi)"
#define MyEditionInstallerBaseName "MetasequoiaIME-Wubi_Setup"
#define MyEditionDataDirMarker ".metasequoiaime-data.wubi"
#define MyOtherEditionRegistryKeys "Software\Metasequoia\MetasequoiaIME-Full|Software\Metasequoia\MetasequoiaIME-Pinyin|Software\Metasequoia\MetasequoiaIME-Japanese|Software\Metasequoia\MetasequoiaIME-Vietnamese|Software\Metasequoia\MetasequoiaIME-Tibetan|Software\Metasequoia\MetasequoiaIME"
#define MyOtherEditionInstallDirs "metasequoiaime-full|metasequoiaime-pinyin|metasequoiaime-japanese|metasequoiaime-vietnamese|metasequoiaime-tibetan|metasequoiaime"
#elif Edition == "japanese"
#define MyEditionAppName "Metasequoia IME 水杉日语"
#define MyEditionAppId "{{41454B5E-8298-42B8-BA6F-5DD2FE559E5E}"
#define MyEditionClsid "{43218C33-7729-47CC-A485-5F43B77F696A}"
#define MyEditionInstallDir "metasequoiaime-japanese"
#define MyEditionRegistryKey "Software\Metasequoia\MetasequoiaIME-Japanese"
#define MyEditionWatchdogTask "Metasequoia IME Watchdog (Japanese)"
#define MyEditionInstallerBaseName "MetasequoiaIME-Japanese_Setup"
#define MyEditionDataDirMarker ".metasequoiaime-data.japanese"
#define MyOtherEditionRegistryKeys "Software\Metasequoia\MetasequoiaIME-Full|Software\Metasequoia\MetasequoiaIME-Pinyin|Software\Metasequoia\MetasequoiaIME-Wubi|Software\Metasequoia\MetasequoiaIME-Vietnamese|Software\Metasequoia\MetasequoiaIME-Tibetan|Software\Metasequoia\MetasequoiaIME"
#define MyOtherEditionInstallDirs "metasequoiaime-full|metasequoiaime-pinyin|metasequoiaime-wubi|metasequoiaime-vietnamese|metasequoiaime-tibetan|metasequoiaime"
#elif Edition == "vietnamese"
#define MyEditionAppName "Metasequoia IME 水杉越南语"
#define MyEditionAppId "{{BA5F9864-3095-469D-BCB5-B0562EB51263}"
#define MyEditionClsid "{0CFED878-B045-4604-8DED-845A7C80CABE}"
#define MyEditionInstallDir "metasequoiaime-vietnamese"
#define MyEditionRegistryKey "Software\Metasequoia\MetasequoiaIME-Vietnamese"
#define MyEditionWatchdogTask "Metasequoia IME Watchdog (Vietnamese)"
#define MyEditionInstallerBaseName "MetasequoiaIME-Vietnamese_Setup"
#define MyEditionDataDirMarker ".metasequoiaime-data.vietnamese"
#define MyOtherEditionRegistryKeys "Software\Metasequoia\MetasequoiaIME-Full|Software\Metasequoia\MetasequoiaIME-Pinyin|Software\Metasequoia\MetasequoiaIME-Wubi|Software\Metasequoia\MetasequoiaIME-Japanese|Software\Metasequoia\MetasequoiaIME-Tibetan|Software\Metasequoia\MetasequoiaIME"
#define MyOtherEditionInstallDirs "metasequoiaime-full|metasequoiaime-pinyin|metasequoiaime-wubi|metasequoiaime-japanese|metasequoiaime-tibetan|metasequoiaime"
#elif Edition == "tibetan"
#define MyEditionAppName "Metasequoia IME 水杉藏文"
#define MyEditionAppId "{{68802231-3EDF-4B67-B80F-DFB95A1BAD01}"
#define MyEditionClsid "{93DEEE80-9145-4257-BF11-957FDFE0A75E}"
#define MyEditionInstallDir "metasequoiaime-tibetan"
#define MyEditionRegistryKey "Software\Metasequoia\MetasequoiaIME-Tibetan"
#define MyEditionWatchdogTask "Metasequoia IME Watchdog (Tibetan)"
#define MyEditionInstallerBaseName "MetasequoiaIME-Tibetan_Setup"
#define MyEditionDataDirMarker ".metasequoiaime-data.tibetan"
#define MyOtherEditionRegistryKeys "Software\Metasequoia\MetasequoiaIME-Full|Software\Metasequoia\MetasequoiaIME-Pinyin|Software\Metasequoia\MetasequoiaIME-Wubi|Software\Metasequoia\MetasequoiaIME-Japanese|Software\Metasequoia\MetasequoiaIME-Vietnamese|Software\Metasequoia\MetasequoiaIME"
#define MyOtherEditionInstallDirs "metasequoiaime-full|metasequoiaime-pinyin|metasequoiaime-wubi|metasequoiaime-japanese|metasequoiaime-vietnamese|metasequoiaime"
#else
#error Unknown edition; use /DEdition= one of full, pinyin, wubi, japanese, vietnamese, tibetan
#endif
