//! 剪贴板历史采集跳过密码管理器内容的判定。
//!
//! 只做判定，不碰 Win32，所以 `tests/clipboard_privacy_policy.rs` 能在任何主机上直接引用本文件测试。格式名与 Server 侧 `platforms/windows/src/clipboard/ClipboardPrivacyPolicy.h` 是同一份名单，两处必须一致；macOS 对应的是 `BackendClipboardCapture.swift` 的 `excludedTypes`。

/// 带这个注册格式的内容不该被任何剪贴板监视程序处理。
pub const EXCLUDE_MONITOR_FORMAT: &str = "ExcludeClipboardContentFromMonitorProcessing";
/// 老一代剪贴板查看器约定的同义标记。
pub const VIEWER_IGNORE_FORMAT: &str = "Clipboard Viewer Ignore";
/// DWORD，值为 0 时内容不进剪贴板历史。
pub const HISTORY_PERMISSION_FORMAT: &str = "CanIncludeInClipboardHistory";
/// DWORD，值为 0 时内容不上传云剪贴板。
pub const CLOUD_PERMISSION_FORMAT: &str = "CanUploadToCloudClipboard";

/// 语音识别文本经剪贴板投递（ctrl_v）时一并写入的注册格式，值都是 DWORD 0：剪贴板监视程序（包括水杉自己的剪贴板历史）跳过这次内容，Win+V 历史和云剪贴板也不保留它。与 Server 侧 `platforms/windows/src/voice/VoiceCommitPolicy.h` 的 `voice_clipboard_markers` 是同一份名单，对应 macOS 写入的 org.nspasteboard.ConcealedType / AutoGeneratedType。
pub const VOICE_CLIPBOARD_MARKERS: [&str; 3] = [
    EXCLUDE_MONITOR_FORMAT,
    HISTORY_PERMISSION_FORMAT,
    CLOUD_PERMISSION_FORMAT,
];

/// 一个 DWORD 许可格式的状态。
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub enum ClipboardPermission {
    /// 剪贴板上没有这个格式。
    #[default]
    Absent,
    Allowed,
    Denied,
}

impl ClipboardPermission {
    /// 剪贴板上出现了许可格式，`data` 是读到的内容（读不到时为 `None`）。读不到或不足一个 DWORD 时按拒绝处理：写下这个格式的程序显然在表态，宁可漏记一条也不把可能的密码写进历史。
    pub fn from_data(data: Option<&[u8]>) -> Self {
        match data.and_then(|bytes| bytes.get(..4)) {
            Some(value) if value.iter().any(|byte| *byte != 0) => Self::Allowed,
            _ => Self::Denied,
        }
    }
}

/// 一次剪贴板变化上观察到的隐私标记。
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct ClipboardPrivacyMarkers {
    pub exclude_from_monitor: bool,
    pub viewer_ignore: bool,
    pub history: ClipboardPermission,
    pub cloud: ClipboardPermission,
}

impl ClipboardPrivacyMarkers {
    /// 任一标记表示不该被记录时返回 true，调用方丢弃这次样本。
    pub fn excluded(self) -> bool {
        self.exclude_from_monitor
            || self.viewer_ignore
            || self.history == ClipboardPermission::Denied
            || self.cloud == ClipboardPermission::Denied
    }
}
