import { clamp } from "../core/number";
import { logo } from "../settings/app-resources";

// Fixed display samples from MSIME-Windows 04a8df56 settings candidate partials.
// These are not user input or candidates generated by the shared runtime.
export const previewSamples = [
  ["你们", "rR"],
  ["你", "rX"],
  ["尼", "uV"],
  ["妮", "nV"],
  ["泥", "dV"],
  ["逆", "zQ"],
  ["拟", "fR"],
  ["腻", "oD"],
  ["拧", "nG"],
] as const;

/** A package background as the preview draws it: an image URL from the bounded host reader, never one from the manifest. */
export type PreviewBackground = {
  url: string;
  fit: "cover" | "contain" | "stretch";
  opacity: number;
};

/** 预览要预留的最高排布：设置页上能切换的排列方式和每页数量里最高的那一种。 */
export type PreviewReserve = { orientation: "horizontal" | "vertical"; count: number };

type SkinCandidatePreviewProps = Parameters<typeof SkinCandidatePreview>[0];

/**
 * 设置页顶部的候选预览：高度按 `reserve` 预留，切换横向／纵向或拖动每页数量时预览框不变高、不变矮，下面的控件就不会在鼠标底下跳动。
 *
 * 预留靠一份不可见的同款样例撑开：它和实际样例叠在同一个网格单元里，用同样的字号、皮肤几何和装饰带，量出来的就是那种排布真实的高度，不必按行高去估算，也就不会裁掉大皮肤或装饰图。实际样例在格子里垂直居中。不传 `reserve` 时与 `SkinCandidatePreview` 完全相同。
 */
export function ReservedCandidatePreview({
  reserve,
  ...props
}: SkinCandidatePreviewProps & { reserve?: PreviewReserve }) {
  if (!reserve) return <SkinCandidatePreview {...props} />;
  return (
    <div className="grid min-w-0 flex-1 grid-cols-[minmax(0,1fr)] items-center justify-items-start [&>*]:[grid-area:1/1]">
      <SkinCandidatePreview {...props} />
      {/* 只为占位：不画图片（装饰图和背景图都是绝对定位，不影响尺寸），始终带拼音行，免得隐藏拼音行时预览变矮。 */}
      <div className="invisible" aria-hidden="true" data-preview-reserve="">
        <SkinCandidatePreview
          orientation={reserve.orientation}
          count={reserve.count}
          preedit
          helpcode={props.helpcode}
          decorated={props.decorated}
          ghost
        />
      </div>
    </div>
  );
}

export function SkinCandidatePreview({
  orientation,
  decorated = false,
  image,
  onImageError,
  background,
  onBackgroundError,
  count = 6,
  preedit = true,
  helpcode = false,
  ghost = false,
}: {
  orientation: "horizontal" | "vertical";
  decorated?: boolean;
  image?: string;
  onImageError?: () => void;
  background?: PreviewBackground;
  onBackgroundError?: () => void;
  count?: number;
  preedit?: boolean;
  /** Off unless the caller says otherwise: the core's default scheme is 全拼, whose helper codes stay out of the candidate window by default. */
  helpcode?: boolean;
  /** 只用来占位的那一份不带 `data-preview-layout`，读预览排布的地方只会找到实际样例。 */
  ghost?: boolean;
}) {
  const horizontal = orientation === "horizontal";
  const visibleCount = Number.isFinite(count) ? clamp(Math.trunc(count), 1, 9) : 6;
  const content = (
    <div className={`container${preedit ? "" : " preedit-hidden"}`}>
      {background && (
        <img
          className="skin-background-image"
          src={background.url}
          alt=""
          style={{
            objectFit: background.fit === "stretch" ? "fill" : background.fit,
            opacity: background.opacity,
          }}
          onError={onBackgroundError}
        />
      )}
      {/* The brand mark leads the top row as it does on every host; with the reading hidden the row is still there, holding only the mark. It sits before the reading's row so the upstream `.pinyin + .row-wrapper` selectors still match. */}
      {!preedit && (
        <div className="row candidate-brand-row">
          <img className="candidate-brand" src={logo} alt="" />
        </div>
      )}
      <div className="row pinyin" hidden={!preedit}>
        {preedit && <img className="candidate-brand" src={logo} alt="" />}
        <div className="text">
          ni'mf
          <span className="cursor" />
        </div>
        <div className="hidden-pinyin">n</div>
      </div>
      {previewSamples.slice(0, visibleCount).map(([text, code], index) => (
        <div
          key={index}
          className={`row-wrapper${horizontal && index === 0 ? " first-row-wrapper" : ""}`}
        >
          <div className={`row cand${index === 0 ? " first" : ""}`}>
            <div className="text">
              <span className={horizontal ? "num" : "cand-no"}>{index + 1}</span>
              {horizontal ? (
                <>
                  {text}
                  {helpcode && <span className="cand-helpcode">({code})</span>}
                </>
              ) : (
                <span className="cand-content">
                  {text}
                  {helpcode && <span className="cand-helpcode">({code})</span>}
                </span>
              )}
            </div>
          </div>
        </div>
      ))}
    </div>
  );
  return (
    <div
      className={`candidate wnd-${horizontal ? "h" : "v"}`}
      data-preview-layout={ghost ? undefined : orientation}
    >
      {decorated ? (
        <div className="containerParent">
          {image && (
            <img className="skin-decoration-image" src={image} alt="" onError={onImageError} />
          )}
          {content}
        </div>
      ) : (
        content
      )}
    </div>
  );
}
