import { clamp } from "../core/number";
import { logo } from "../settings/app-resources";

// Fixed display samples from MSIME-Windows 04a8df56 settings candidate partials.
// These are not user input or candidates generated by the shared runtime.
const samples = [
  ["你们", "rR"],
  ["你", "rX"],
  ["尼", "uV"],
  ["妮", "nV"],
  ["泥", "dV"],
  ["逆", "zQ"],
  ["拟", "fR"],
  ["腻", "oD"],
  ["拧", "nG"],
] as const;

/** A package background as the preview draws it: an image URL from the bounded host reader, never one from the manifest. */
export type PreviewBackground = {
  url: string;
  fit: "cover" | "contain" | "stretch";
  opacity: number;
};

export function SkinCandidatePreview({
  orientation,
  decorated = false,
  image,
  onImageError,
  background,
  onBackgroundError,
  count = 6,
  preedit = true,
  helpcode = false,
}: {
  orientation: "horizontal" | "vertical";
  decorated?: boolean;
  image?: string;
  onImageError?: () => void;
  background?: PreviewBackground;
  onBackgroundError?: () => void;
  count?: number;
  preedit?: boolean;
  /** Off unless the caller says otherwise: the core's default scheme is 全拼, whose helper codes stay out of the candidate window by default. */
  helpcode?: boolean;
}) {
  const horizontal = orientation === "horizontal";
  const visibleCount = Number.isFinite(count) ? clamp(Math.trunc(count), 1, 9) : 6;
  const content = (
    <div className={`container${preedit ? "" : " preedit-hidden"}`}>
      {background && (
        <img
          className="skin-background-image"
          src={background.url}
          alt=""
          style={{
            objectFit: background.fit === "stretch" ? "fill" : background.fit,
            opacity: background.opacity,
          }}
          onError={onBackgroundError}
        />
      )}
      {/* The brand mark leads the top row as it does on every host; with the reading hidden the row is still there, holding only the mark. It sits before the reading's row so the upstream `.pinyin + .row-wrapper` selectors still match. */}
      {!preedit && (
        <div className="row candidate-brand-row">
          <img className="candidate-brand" src={logo} alt="" />
        </div>
      )}
      <div className="row pinyin" hidden={!preedit}>
        {preedit && <img className="candidate-brand" src={logo} alt="" />}
        <div className="text">
          ni'mf
          <span className="cursor" />
        </div>
        <div className="hidden-pinyin">n</div>
      </div>
      {samples.slice(0, visibleCount).map(([text, code], index) => (
        <div
          key={index}
          className={`row-wrapper${horizontal && index === 0 ? " first-row-wrapper" : ""}`}
        >
          <div className={`row cand${index === 0 ? " first" : ""}`}>
            <div className="text">
              <span className={horizontal ? "num" : "cand-no"}>{index + 1}</span>
              {horizontal ? (
                <>
                  {text}
                  {helpcode && <span className="cand-helpcode">({code})</span>}
                </>
              ) : (
                <span className="cand-content">
                  {text}
                  {helpcode && <span className="cand-helpcode">({code})</span>}
                </span>
              )}
            </div>
          </div>
        </div>
      ))}
    </div>
  );
  return (
    <div className={`candidate wnd-${horizontal ? "h" : "v"}`} data-preview-layout={orientation}>
      {decorated ? (
        <div className="containerParent">
          {image && (
            <img className="skin-decoration-image" src={image} alt="" onError={onImageError} />
          )}
          {content}
        </div>
      ) : (
        content
      )}
    </div>
  );
}
