import { clamp } from "../core/number";

// Fixed display samples from MSIME-Windows 04a8df56 settings candidate partials.
// These are not user input or candidates generated by the shared runtime.
const samples = [
  ["你们", "rR"],
  ["你", "rX"],
  ["尼", "uV"],
  ["妮", "nV"],
  ["泥", "dV"],
  ["逆", "zQ"],
  ["拟", "fR"],
  ["腻", "oD"],
  ["拧", "nG"],
] as const;

export function SkinCandidatePreview({
  orientation,
  decorated = false,
  image,
  onImageError,
  count = 6,
  preedit = true,
  helpcode = true,
}: {
  orientation: "horizontal" | "vertical";
  decorated?: boolean;
  image?: string;
  onImageError?: () => void;
  count?: number;
  preedit?: boolean;
  helpcode?: boolean;
}) {
  const horizontal = orientation === "horizontal";
  const visibleCount = Number.isFinite(count) ? clamp(Math.trunc(count), 1, 9) : 6;
  const content = (
    <div className={`container${preedit ? "" : " preedit-hidden"}`}>
      <div className="row pinyin" hidden={!preedit}>
        <div className="text">
          ni'mf
          <span className="cursor" />
        </div>
        <div className="hidden-pinyin">n</div>
      </div>
      {samples.slice(0, visibleCount).map(([text, code], index) => (
        <div
          key={index}
          className={`row-wrapper${horizontal && index === 0 ? " first-row-wrapper" : ""}`}
        >
          <div className={`row cand${index === 0 ? " first" : ""}`}>
            <div className="text">
              <span className={horizontal ? "num" : "cand-no"}>{index + 1}</span>
              {horizontal ? (
                <>
                  {text}
                  {helpcode && <span className="cand-helpcode">({code})</span>}
                </>
              ) : (
                <span className="cand-content">
                  {text}
                  {helpcode && <span className="cand-helpcode">({code})</span>}
                </span>
              )}
            </div>
          </div>
        </div>
      ))}
    </div>
  );
  return (
    <div className={`candidate wnd-${horizontal ? "h" : "v"}`} data-preview-layout={orientation}>
      {decorated ? (
        <div className="containerParent">
          {image && (
            <img className="skin-decoration-image" src={image} alt="" onError={onImageError} />
          )}
          {content}
        </div>
      ) : (
        content
      )}
    </div>
  );
}
