//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MetasequoiaIME.rc
//
#define SUBLANG_ENGLISH_US 0x01
#define LANG_ENGLISH 0x09
#define VS_VERSION_INFO 1
#define IDIS_METASEQUOIAIME 12
#define IDS_DEFAULT_FONT 13
#define IDS_IME_MODE 20
#define IDI_IME_MODE_ON 21
#define IDI_IME_MODE_OFF 22
#define IDS_DOUBLE_SINGLE_BYTE 23
#define IDI_DOUBLE_SINGLE_BYTE_ON 24
#define IDI_DOUBLE_SINGLE_BYTE_OFF 25
#define IDS_PUNCTUATION 26
#define IDI_PUNCTUATION_ON 27
#define IDI_PUNCTUATION_OFF 28
#define IDI_IME_MODE_ON_DARK 29
#define IDI_IME_MODE_OFF_DARK 30
#define IDI_IME_MODE_ON_JP 31
#define IDI_IME_MODE_ON_JP_DARK 32
#define IDI_IME_MODE_CAP 33
#define IDI_IME_MODE_CAP_DARK 34
#define IDI_IME_MODE_ON_KR 35
#define IDI_IME_MODE_ON_KR_DARK 36
#define IDI_IME_MODE_ON_SHUANGPIN 37
#define IDI_IME_MODE_ON_SHUANGPIN_DARK 38
#define IDI_IME_MODE_ON_WUBI 39
#define IDI_IME_MODE_ON_WUBI_DARK 40
#define IDI_IME_MODE_ON_CANTONESE 41
#define IDI_IME_MODE_ON_CANTONESE_DARK 42
#define IDI_IME_MODE_ON_ZHUYIN 43
#define IDI_IME_MODE_ON_ZHUYIN_DARK 44
#define IDI_IME_MODE_ON_VIETNAMESE 45
#define IDI_IME_MODE_ON_VIETNAMESE_DARK 46
#define IDI_IME_MODE_ON_TIBETAN 47
#define IDI_IME_MODE_ON_TIBETAN_DARK 48
#define IDI_IME_MODE_ON_STROKE 49
#define IDI_IME_MODE_ON_STROKE_DARK 50
// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE 108
#define _APS_NEXT_COMMAND_VALUE 40001
#define _APS_NEXT_CONTROL_VALUE 1000
#define _APS_NEXT_SYMED_VALUE 101
#endif
#endif
