# 本次构建的产品版本（shared/contracts/editions.json 的 id）。shared/contracts/msime_edition.h 按这里定义的 MSIME_EDITION_<ID> 选出该版本的 CLSID、管道名、注册表键和目录名；TSF DLL、Server、看门狗和 prepare 工具在编译期就绑定到一个版本，所以每个版本各编一次。缺省是 full，与引入版本之前的构建完全相同。
include_guard(GLOBAL)
set(MSIME_EDITION "full" CACHE STRING "Product edition to build (an id in shared/contracts/editions.json with a Windows section)")
file(READ "${CMAKE_CURRENT_LIST_DIR}/../../shared/contracts/editions.json" msime_editions_json)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${CMAKE_CURRENT_LIST_DIR}/../../shared/contracts/editions.json")
string(JSON msime_edition_count LENGTH "${msime_editions_json}" editions)
set(msime_edition_known OFF)
set(msime_edition_ids "")
math(EXPR msime_edition_last "${msime_edition_count} - 1")
foreach(msime_edition_index RANGE ${msime_edition_last})
  string(JSON msime_edition_id GET "${msime_editions_json}" editions ${msime_edition_index} id)
  string(JSON msime_edition_windows TYPE "${msime_editions_json}" editions ${msime_edition_index} platforms windows)
  if(msime_edition_windows STREQUAL "OBJECT")
    list(APPEND msime_edition_ids "${msime_edition_id}")
    if(msime_edition_id STREQUAL MSIME_EDITION)
      set(msime_edition_known ON)
    endif()
  endif()
endforeach()
if(NOT msime_edition_known)
  message(FATAL_ERROR "MSIME_EDITION=${MSIME_EDITION} is not an edition with Windows identifiers; choose one of: ${msime_edition_ids}")
endif()
string(TOUPPER "${MSIME_EDITION}" msime_edition_macro)
add_compile_definitions(MSIME_EDITION_${msime_edition_macro})
