#!/usr/bin/env python3
"""从 `resources/desktop-dictionary.lock.json` 生成各资源组件和各版本的资源锁。

`resources/desktop-dictionary.lock.json` 仍是词库来源、长度和 SHA-256 的唯一事实源，换词库版本时只改它；这里生成的文件都是它的机械子集，提交进仓库，Rust 用 `include_str!` 嵌入，平台打包脚本直接读取，不需要构建期生成：

- `resources/components/<组件>.lock.json`：按 `shared/contracts/editions.json` 的 `resource_components` 拆出的每个组件；
- `resources/editions/<版本>.lock.json`：每个不是 full 的版本，内容是它的 `resources.components` 的并集。full 的锁就是 `resources/desktop-dictionary.lock.json` 本身，不另生成一份，因此 full 的资源目录、校验和用户词库代次与引入版本之前完全相同。

生成的锁保留原文件的 `source_commit`，条目保持原文件的顺序和每个字段的原值，格式与原文件相同（两个空格缩进、末尾一个换行）。所以全部组件的并集逐字节等于原文件，`scripts/test-editions.py` 会检查这一点。

换词库或改了组件、版本之后运行，再提交生成的文件：

    python3 scripts/editions.py gen-locks

`--check` 只比较不写入，有差异时以非零状态退出；`scripts/test-editions.py` 在 contracts job 里做同样的比较。
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
EDITIONS = ROOT / "shared/contracts/editions.json"
DESKTOP_LOCK = ROOT / "resources/desktop-dictionary.lock.json"
COMPONENTS_DIRECTORY = ROOT / "resources/components"
EDITIONS_DIRECTORY = ROOT / "resources/editions"
FULL = "full"


def render(lock: dict) -> str:
    """与 `resources/desktop-dictionary.lock.json` 相同的格式。"""
    return json.dumps(lock, indent=2, ensure_ascii=False) + "\n"


def subset(desktop: dict, names: set[str]) -> dict:
    """`desktop` 里名字在 `names` 中的条目，顺序和字段与原文件相同。"""
    return {
        "source_commit": desktop["source_commit"],
        "artifacts": [artifact for artifact in desktop["artifacts"] if artifact["name"] in names],
    }


def edition_lock_path(edition_id: str) -> pathlib.Path:
    """版本的资源锁路径：full 是原文件，其他版本在 `resources/editions/` 下。与 `crates/client-core/src/edition.rs` 的 `Edition::resource_lock` 一致。"""
    if edition_id == FULL:
        return DESKTOP_LOCK
    return EDITIONS_DIRECTORY / f"{edition_id}.lock.json"


def generated_locks(table: dict, desktop: dict) -> dict[pathlib.Path, str]:
    """所有应当提交的生成文件：路径到内容。不含 full 的锁，它不是生成的。"""
    components: dict[str, list[str]] = table["resource_components"]
    files: dict[pathlib.Path, str] = {}
    for component, names in components.items():
        files[COMPONENTS_DIRECTORY / f"{component}.lock.json"] = render(subset(desktop, set(names)))
    for edition in table["editions"]:
        if edition["id"] == FULL:
            continue
        names = {name for component in edition["resources"]["components"] for name in components[component]}
        files[edition_lock_path(edition["id"])] = render(subset(desktop, names))
    return files


def union_of_components(table: dict, desktop: dict) -> str:
    """全部组件的并集，格式与生成文件相同；应当逐字节等于原文件。"""
    names = {name for files in table["resource_components"].values() for name in files}
    return render(subset(desktop, names))


def drift(files: dict[pathlib.Path, str]) -> list[str]:
    """已提交的文件与生成结果的差异，以及两个生成目录里多出来的文件。"""
    problems = []
    for path, text in files.items():
        relative = path.relative_to(ROOT)
        if not path.is_file():
            problems.append(f"{relative} is missing")
        elif path.read_text(encoding="utf-8") != text:
            problems.append(f"{relative} differs from what scripts/editions.py generates")
    for directory in [COMPONENTS_DIRECTORY, EDITIONS_DIRECTORY]:
        if directory.is_dir():
            for path in sorted(directory.iterdir()):
                if path not in files:
                    problems.append(f"{path.relative_to(ROOT)} is not generated by scripts/editions.py; remove it")
    return problems


def load() -> tuple[dict, dict]:
    table = json.loads(EDITIONS.read_text(encoding="utf-8"))
    desktop = json.loads(DESKTOP_LOCK.read_text(encoding="utf-8"))
    return table, desktop


def gen_locks(check: bool) -> int:
    table, desktop = load()
    files = generated_locks(table, desktop)
    if check:
        problems = drift(files)
        for problem in problems:
            print(f"FAIL: {problem}")
        return 1 if problems else 0
    for directory in [COMPONENTS_DIRECTORY, EDITIONS_DIRECTORY]:
        directory.mkdir(parents=True, exist_ok=True)
        # 组件或版本改名、删除后，旧文件不能留在目录里被打包脚本读到。
        for path in directory.iterdir():
            if path not in files:
                path.unlink()
    for path, text in files.items():
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    commands = parser.add_subparsers(dest="command", required=True)
    locks = commands.add_parser("gen-locks", help="生成 resources/components 和 resources/editions 下的资源锁")
    locks.add_argument("--check", action="store_true", help="只比较，不写入")
    args = parser.parse_args()
    if args.command == "gen-locks":
        return gen_locks(args.check)
    return 2


if __name__ == "__main__":
    sys.exit(main())
