//! `msime-cantonese.db`：粤语方案的粤拼词库，按 `msime_engine::language_dictionary` 定义的结构写出。数据是 rime-cantonese（CC BY 4.0，见 `resources/licenses/rime-cantonese-CC-BY-4.0.txt`）在 `resources/dictionary-sources.lock.json` 的 `rime-cantonese` 引用所记提交的文件，由 msime-dictionary 原样收在 `sources/cantonese/` 下；构建从 `--dictionary` checkout 读取，并按它的 `upstream.lock.json` 校验。
//!
//! Four files are read: `jyut6ping3.chars.dict.yaml` (one character, its toned reading and an optional `N%` share of that character's use per row), `jyut6ping3.words.dict.yaml` (one word and its toned readings per row), `essay-cantonese.txt` (Rime's word frequency list, one `text<TAB>count` per line) and `hkcancor-word-counts.txt` (word counts of the Hong Kong Cantonese Corpus, CC BY 4.0, generated by `hkcancor.rs` into msime-dictionary). `jyut6ping3.maps.dict.yaml` is ODbL and `jyut6ping3.phrase.dict.yaml` has no readings and no clear provenance, so neither is pinned or read; neither is `jyut6ping3.lettered.dict.yaml`.
//!
//! The scheme types toneless Jyutping, so every reading loses its tone digit and an entry's key is its toneless syllables joined by one space (`nei hou`). Readings that differ only in tone collapse into one entry with the largest weight. A word weighs its essay count. The essay is mostly written Chinese and does not list about two in five words of the words file, the commonest colloquial ones among them (我哋, 佢哋, 嗰啲, 食咗). Such a word that the corpus counts weighs its corpus count times `corpus_scale`, the median ratio between the essay count and the corpus count of the words both list, which puts the corpus counts on the essay's scale (我哋, 446 tokens in the corpus, lands near 點解). A word the corpus counts fewer than `CORPUS_MIN_COUNT` times is held one below the lightest essay-listed word of its key, so a variant spelling or segmentation accident seen once (物証 beside 物證) does not overtake a word the essay counts. Any other unlisted word weighs `unlisted_word_weight`: 1 plus the base-2 logarithm of its rarest character's essay count, which orders such homophones by how common their characters are while staying far below the counts the essay gives the words it lists (most of them at least 100). The corpus spells with Hong Kong forms (為, 眾) where the words file follows OpenCC (爲, 衆), so a word whose spelling differs between the two keeps the fallback weight. A character weighs its essay count scaled by the row's share when the row gives one, never below 1.
//!
//! The words file lacks some of the commonest words because Rime composes them from characters at typing time (你好 is one), and the engine does not compose sentences. So an essay word the words file does not list becomes an entry too when the essay counts it at least `ESSAY_WORD_MIN_COUNT` times and each of its characters has exactly one toneless reading in the characters file, which makes its key certain.
//!
//! The syllable inventory is every toneless syllable some key uses, so every entry stays typable; the words file uses a few colloquial syllables (`fi`, `za`, `gwek`) that no character row has.

use std::collections::{BTreeMap, BTreeSet, HashMap, HashSet};
use std::path::Path;

use anyhow::{bail, Context, Result};
use msime_engine::language_dictionary;
use rusqlite::{Connection, OpenFlags};

use crate::sqlite;

pub const CHARACTERS: &str = "sources/cantonese/jyut6ping3.chars.dict.yaml";
pub const WORDS: &str = "sources/cantonese/jyut6ping3.words.dict.yaml";
pub const ESSAY: &str = "sources/cantonese/essay-cantonese.txt";
pub const CORPUS: &str = crate::hkcancor::OUTPUT;
/// The sources lock reference whose commit is recorded as the database's `source_commit`.
pub const REFERENCE: &str = "rime-cantonese";
/// The SPDX identifier recorded as the database's `license`.
pub const LICENSE: &str = "CC-BY-4.0";
pub const DATABASE: &str = "msime-cantonese.db";
/// The licence text in `resources/licenses/` and the name it ships under beside the database.
pub const LICENSE_SOURCE: &str = "rime-cantonese-CC-BY-4.0.txt";
pub const LICENSE_NAME: &str = "msime-rime_cantonese_LICENSE.txt";

/// The essay count from which a word missing from the words file is added. The essay's counts are scaled scores rather than raw counts (the median word of the words file scores 900), and 1000 keeps about five thousand frequent words such as 你好 while leaving out the long tail of novel names and segmentation fragments the essay also lists.
pub const ESSAY_WORD_MIN_COUNT: i64 = 1000;

/// The corpus count from which a word may rank ahead of a word the essay lists on the same key. The corpus has about 160 thousand tokens, so a word seen once or twice there is as likely a variant spelling (物証, 遊盪) or a segmentation accident (唔知 is split while 唔止 is kept whole) as a common word; below this count its corpus weight is held one below the lightest essay-listed word of its key.
pub const CORPUS_MIN_COUNT: i64 = 3;

/// The floors `verify` enforces on a release build.
pub const FLOORS: Floors = Floors {
    syllables: 600,
    characters: 25_000,
    words: 90_000,
};

/// Keys whose top three entries must include the text, as a check against gross ranking errors.
pub const EXPECTED: [(&str, &str); 2] = [("nei hou", "你好"), ("gwong dung waa", "廣東話")];

#[derive(Debug, Clone, Copy)]
pub struct Floors {
    pub syllables: usize,
    pub characters: usize,
    pub words: usize,
}

/// One row of the characters or words file.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Row<'a> {
    pub text: &'a str,
    /// Toneless syllables.
    pub syllables: Vec<&'a str>,
    /// The row's share of the character's use in percent, when the row gives one.
    pub percent: Option<i64>,
}

#[derive(Debug, Default)]
pub struct Dictionary {
    pub syllables: BTreeSet<String>,
    /// `(key, text)` to weight.
    pub entries: BTreeMap<(String, String), i64>,
    /// Entries that came from the characters file, the words file and the essay.
    pub characters: usize,
    pub words: usize,
    pub essay_words: usize,
    /// Words-file entries the essay does not list that took their weight from the corpus, and the factor that put the corpus counts on the essay's scale.
    pub corpus_words: usize,
    pub corpus_scale: i64,
    /// Corpus-weighted words below `CORPUS_MIN_COUNT` whose weight was held below an essay-listed word of their key.
    pub corpus_capped: usize,
}

/// The rows after the YAML header, which ends at the `...` line, with their 1-based line numbers. Blank lines and `#` comments are skipped.
fn body<'a>(name: &str, source: &'a str) -> Result<impl Iterator<Item = (usize, &'a str)>> {
    let mut lines = source.lines().enumerate();
    if !lines.by_ref().any(|(_, line)| line == "...") {
        bail!("{name}: no `...` line ends the YAML header");
    }
    Ok(lines
        .filter(|(_, line)| !line.is_empty() && !line.starts_with('#'))
        .map(|(index, line)| (index + 1, line)))
}

/// The toneless syllables of a space-separated toned reading such as `nei5 hou2`.
fn toneless<'a>(name: &str, line: usize, reading: &'a str) -> Result<Vec<&'a str>> {
    reading
        .split(' ')
        .map(|syllable| {
            let letters = syllable
                .strip_suffix(|c: char| ('1'..='6').contains(&c))
                .filter(|letters| {
                    !letters.is_empty() && letters.bytes().all(|b| b.is_ascii_lowercase())
                });
            letters.with_context(|| {
                format!("{name}: line {line}: {syllable:?} is not a toned Jyutping syllable")
            })
        })
        .collect()
}

/// `jyut6ping3.chars.dict.yaml`: `character<TAB>reading[<TAB>N%]`.
pub fn parse_characters(source: &str) -> Result<Vec<Row<'_>>> {
    let mut rows = Vec::new();
    for (line, row) in body(CHARACTERS, source)? {
        let fields: Vec<&str> = row.split('\t').collect();
        let (text, reading, percent) = match fields[..] {
            [text, reading] => (text, reading, None),
            [text, reading, percent] => (text, reading, Some(percent)),
            _ => bail!("{CHARACTERS}: line {line} is not character<TAB>reading[<TAB>N%]"),
        };
        if text.chars().count() != 1 {
            bail!("{CHARACTERS}: line {line}: {text:?} is not one character");
        }
        // A few unit characters read as two syllables (兡 baak3 hak1, a hectogram).
        let syllables = toneless(CHARACTERS, line, reading)?;
        let percent = percent
            .map(|percent| {
                percent
                    .strip_suffix('%')
                    .and_then(|number| number.parse::<i64>().ok())
                    .filter(|number| (0..=100).contains(number))
                    .with_context(|| {
                        format!("{CHARACTERS}: line {line}: {percent:?} is not a percentage")
                    })
            })
            .transpose()?;
        rows.push(Row {
            text,
            syllables,
            percent,
        });
    }
    Ok(rows)
}

/// `jyut6ping3.words.dict.yaml`: `word<TAB>reading`.
pub fn parse_words(source: &str) -> Result<Vec<Row<'_>>> {
    let mut rows = Vec::new();
    for (line, row) in body(WORDS, source)? {
        let fields: Vec<&str> = row.split('\t').collect();
        let [text, reading] = fields[..] else {
            bail!("{WORDS}: line {line} is not word<TAB>reading");
        };
        if text.is_empty() {
            bail!("{WORDS}: line {line} has no word");
        }
        rows.push(Row {
            text,
            syllables: toneless(WORDS, line, reading)?,
            percent: None,
        });
    }
    Ok(rows)
}

/// `essay-cantonese.txt`: `text<TAB>count`. A text listed twice keeps its larger count.
pub fn parse_essay(source: &str) -> Result<HashMap<&str, i64>> {
    let mut counts = HashMap::new();
    for (index, row) in source.lines().enumerate() {
        if row.is_empty() {
            continue;
        }
        let parsed = row.split_once('\t').and_then(|(text, count)| {
            Some((text, count.parse::<i64>().ok().filter(|count| *count >= 0)?))
        });
        let Some((text, count)) = parsed.filter(|(text, _)| !text.is_empty()) else {
            bail!("{ESSAY}: line {} is not text<TAB>count", index + 1);
        };
        let kept = counts.entry(text).or_insert(count);
        *kept = (*kept).max(count);
    }
    Ok(counts)
}

impl Dictionary {
    fn insert(&mut self, key: String, text: &str, weight: i64) {
        let slot = self.entries.entry((key, text.to_owned())).or_insert(weight);
        *slot = (*slot).max(weight);
    }
}

/// The weight of a word the essay does not list: 1 plus the base-2 logarithm of the essay count of its rarest character, or 1 when one of its characters is not counted at all. Real counts top out near 2^24, so this stays below 64 and under almost every count the essay gives a listed word.
fn unlisted_word_weight(text: &str, essay: &HashMap<&str, i64>) -> i64 {
    let mut buffer = [0; 4];
    let rarest = text
        .chars()
        .map(|character| {
            essay
                .get(&*character.encode_utf8(&mut buffer))
                .copied()
                .unwrap_or(0)
        })
        .min()
        .unwrap_or(0);
    1 + rarest.checked_ilog2().map_or(0, i64::from)
}

/// The lower median of `essay count / corpus count` (integer division) over the words both list, or 1 when they share none.
fn corpus_scale(essay: &HashMap<&str, i64>, corpus: &HashMap<&str, i64>) -> i64 {
    let mut ratios: Vec<i64> = corpus
        .iter()
        .filter_map(|(word, count)| Some(essay.get(word)? / count))
        .collect();
    ratios.sort_unstable();
    ratios
        .get(ratios.len().saturating_sub(1) / 2)
        .copied()
        .unwrap_or(1)
        .max(1)
}

/// The dictionary of the four parsed inputs.
pub fn build(
    characters: &[Row],
    words: &[Row],
    essay: &HashMap<&str, i64>,
    corpus: &HashMap<&str, i64>,
) -> Dictionary {
    let mut dictionary = Dictionary {
        corpus_scale: corpus_scale(essay, corpus),
        ..Dictionary::default()
    };
    // Each character's toneless keys, to give an essay word a key when each of its characters has only one.
    let mut readings: HashMap<&str, HashSet<String>> = HashMap::new();
    for row in characters {
        let count = essay.get(row.text).copied().unwrap_or(0);
        let weight = row
            .percent
            .map_or(count, |percent| count.saturating_mul(percent) / 100)
            .max(1);
        let key = row.syllables.join(" ");
        readings.entry(row.text).or_default().insert(key.clone());
        dictionary.insert(key, row.text, weight);
    }
    dictionary.characters = dictionary.entries.len();

    let mut listed = HashSet::new();
    let mut corpus_weighted = HashSet::new();
    // The lightest essay-listed word on each key, and the thinly attested corpus words with their fallback weights, which are held below it once the essay words below are added too.
    let mut lightest_essay: HashMap<String, i64> = HashMap::new();
    let mut thin = Vec::new();
    for row in words {
        let key = row.syllables.join(" ");
        let weight = match (essay.get(row.text), corpus.get(row.text)) {
            (Some(&count), _) => {
                let lightest = lightest_essay.entry(key.clone()).or_insert(count);
                *lightest = (*lightest).min(count);
                count
            }
            (None, Some(&count)) => {
                corpus_weighted.insert(row.text);
                let fallback = unlisted_word_weight(row.text, essay);
                if count < CORPUS_MIN_COUNT {
                    thin.push((key.clone(), row.text, fallback));
                }
                count.saturating_mul(dictionary.corpus_scale).max(fallback)
            }
            (None, None) => unlisted_word_weight(row.text, essay),
        };
        dictionary.insert(key, row.text, weight);
        listed.insert(row.text);
    }
    dictionary.corpus_words = corpus_weighted.len();
    dictionary.words = dictionary.entries.len() - dictionary.characters;

    for (&text, &count) in essay {
        if count < ESSAY_WORD_MIN_COUNT || text.chars().count() < 2 || listed.contains(text) {
            continue;
        }
        let keys: Option<Vec<&str>> = text
            .chars()
            .map(|character| {
                let mut buffer = [0; 4];
                let readings = readings.get(&*character.encode_utf8(&mut buffer))?;
                let mut only = readings.iter();
                match (only.next(), only.next()) {
                    (Some(key), None) => Some(key.as_str()),
                    _ => None,
                }
            })
            .collect();
        if let Some(keys) = keys {
            let key = keys.join(" ");
            let lightest = lightest_essay.entry(key.clone()).or_insert(count);
            *lightest = (*lightest).min(count);
            dictionary.insert(key, text, count);
        }
    }
    dictionary.essay_words = dictionary.entries.len() - dictionary.characters - dictionary.words;

    for (key, text, fallback) in thin {
        let Some(&lightest) = lightest_essay.get(&key) else {
            continue;
        };
        let weight = dictionary
            .entries
            .get_mut(&(key, text.to_owned()))
            .expect("every thin corpus word was inserted");
        let capped = (*weight).min(lightest - 1).max(fallback);
        if capped < *weight {
            *weight = capped;
            dictionary.corpus_capped += 1;
        }
    }

    dictionary.syllables = dictionary
        .entries
        .keys()
        .flat_map(|(key, _)| key.split(' '))
        .map(str::to_owned)
        .collect();
    dictionary
}

/// Writes `dictionary` to `path` in the engine's language dictionary schema, replacing any earlier file, and freezes it so the same inputs give the same bytes.
pub fn write(dictionary: &Dictionary, path: &Path, source_commit: &str) -> Result<()> {
    if path.exists() {
        std::fs::remove_file(path).with_context(|| format!("removing {}", path.display()))?;
    }
    let mut connection = sqlite::open(path)?;
    connection.execute_batch(language_dictionary::SCHEMA)?;
    let transaction = connection.transaction()?;
    {
        let mut metadata = transaction.prepare("INSERT INTO metadata VALUES (?1, ?2)")?;
        for (name, value) in [
            (
                language_dictionary::METADATA_FORMAT_VERSION,
                language_dictionary::FORMAT_VERSION.to_string().as_str(),
            ),
            (language_dictionary::METADATA_SOURCE_COMMIT, source_commit),
            (language_dictionary::METADATA_LICENSE, LICENSE),
        ] {
            metadata.execute((name, value))?;
        }
        let mut syllables = transaction.prepare("INSERT INTO syllables VALUES (?1)")?;
        for syllable in &dictionary.syllables {
            syllables.execute((syllable,))?;
        }
        let mut entries = transaction.prepare("INSERT INTO entries VALUES (?1, ?2, ?3)")?;
        for ((key, text), weight) in &dictionary.entries {
            entries.execute((key, text, weight))?;
        }
    }
    transaction.commit()?;
    sqlite::analyze(&connection, false)?;
    sqlite::integrity_check(&connection)?;
    drop(connection);
    sqlite::freeze(path)
}

/// What `verify` counted in a written database.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Counts {
    pub syllables: usize,
    pub characters: usize,
    pub words: usize,
}

/// Opens a written database the way the engine does and fails when it is below `floors` or a key of `EXPECTED` lacks its text in the top three.
pub fn verify(path: &Path, floors: Floors) -> Result<Counts> {
    let dictionary = language_dictionary::open_read_only(path)
        .map_err(|error| anyhow::anyhow!("{}: {error}", path.display()))?;
    let connection = Connection::open_with_flags(path, OpenFlags::SQLITE_OPEN_READ_ONLY)
        .with_context(|| format!("opening {}", path.display()))?;
    let count = |sql: &str| -> Result<usize> {
        let count: i64 = connection.query_row(sql, [], |row| row.get(0))?;
        Ok(usize::try_from(count)?)
    };
    let counts = Counts {
        syllables: count("SELECT count(*) FROM syllables")?,
        characters: count("SELECT count(*) FROM entries WHERE length(text) = 1")?,
        words: count("SELECT count(*) FROM entries WHERE length(text) > 1")?,
    };
    for (what, found, floor) in [
        ("syllables", counts.syllables, floors.syllables),
        ("character entries", counts.characters, floors.characters),
        ("word entries", counts.words, floors.words),
    ] {
        if found < floor {
            bail!(
                "{}: {found} {what}, below the floor of {floor}",
                path.display()
            );
        }
    }
    for (key, text) in EXPECTED {
        let top = dictionary
            .lookup(key, 3)
            .map_err(|error| anyhow::anyhow!("{}: {error}", path.display()))?;
        if !top.iter().any(|entry| entry.text == text) {
            let found: Vec<&str> = top.iter().map(|entry| entry.text.as_str()).collect();
            bail!(
                "{}: {key:?} offers {found:?} first, without {text}",
                path.display()
            );
        }
    }
    Ok(counts)
}

#[cfg(test)]
mod tests {
    use super::*;

    const HEADER: &str = "# Rime dictionary\n# encoding: utf-8\n\n---\nname: jyut6ping3.chars\nversion: \"2026.08.10\"\nsort: by_weight\n...\n\n";

    fn characters_source() -> String {
        format!("{HEADER}你\tnei5\n妳\tnei5\n好\thou2\n好\thou3\t40%\n號\thou6\t0%\n廣\tgwong2\n東\tdung1\n話\twaa6\t80%\n話\twaa2\t20%\n呢\tne1\n呢\tnei4\t5%\n")
    }

    fn words_source() -> String {
        format!("{HEADER}廣東話\tgwong2 dung1 waa2\n廣東話\tgwong2 dung1 waa6\n你哋\tnei5 dei6\nfi li fe le\tfi4 li1 fe4 le4\n")
    }

    const ESSAY_TEXT: &str =
        "你\t7000\n好\t5000\n話\t900\n呢\t2000\n廣東話\t6851\n你好\t21493\n好呢\t3000\n你哋\t40\n號\t10\n你好\t5\n";

    fn entries(dictionary: &Dictionary) -> Vec<(&str, &str, i64)> {
        dictionary
            .entries
            .iter()
            .map(|((key, text), weight)| (key.as_str(), text.as_str(), *weight))
            .collect()
    }

    fn sample() -> Dictionary {
        let characters = characters_source();
        let words = words_source();
        build(
            &parse_characters(&characters).unwrap(),
            &parse_words(&words).unwrap(),
            &parse_essay(ESSAY_TEXT).unwrap(),
            &HashMap::new(),
        )
    }

    #[test]
    fn rows_after_the_header_lose_their_tones() {
        let characters = characters_source();
        let rows = parse_characters(&characters).unwrap();
        assert_eq!(rows.len(), 11);
        assert_eq!(
            rows[3],
            Row {
                text: "好",
                syllables: vec!["hou"],
                percent: Some(40)
            }
        );
        let words = words_source();
        let rows = parse_words(&words).unwrap();
        assert_eq!(rows[0].syllables, ["gwong", "dung", "waa"]);
        assert_eq!(rows[3].text, "fi li fe le");
    }

    #[test]
    fn weights_follow_the_essay_and_the_share_of_use() {
        let dictionary = sample();
        assert_eq!(
            entries(&dictionary),
            [
                ("dung", "東", 1),
                ("fi li fe le", "fi li fe le", 1),
                ("gwong", "廣", 1),
                ("gwong dung waa", "廣東話", 6851),
                // 好 is hou2 (5000) and hou3 at 40% (2000); the tones collapse into the larger weight.
                ("hou", "好", 5000),
                // 0% of 10 floors at 1.
                ("hou", "號", 1),
                ("ne", "呢", 2000),
                ("nei", "你", 7000),
                // 5% of 2000.
                ("nei", "呢", 100),
                ("nei", "妳", 1),
                ("nei dei", "你哋", 40),
                // Every character of 你好 has one toneless reading and the essay counts it often enough; the larger of its two counts wins.
                ("nei hou", "你好", 21493),
                // 80% of 900, the larger share of waa2 and waa6.
                ("waa", "話", 720),
            ]
        );
        // 好呢 is frequent but 呢 reads ne or nei, so its key is uncertain and it stays out.
        assert!(!dictionary.entries.keys().any(|(_, text)| text == "好呢"));
        assert_eq!(
            (
                dictionary.characters,
                dictionary.words,
                dictionary.essay_words
            ),
            (9, 3, 1)
        );
    }

    #[test]
    fn unlisted_homophone_words_follow_their_rarest_character() {
        let characters = format!("{HEADER}食\tsik6\n識\tsik1\n咗\tzo2\n");
        let words = format!("{HEADER}識咗\tsik1 zo2\n食咗\tsik6 zo2\n");
        let dictionary = build(
            &parse_characters(&characters).unwrap(),
            &parse_words(&words).unwrap(),
            &parse_essay("食\t873763\n識\t379707\n咗\t1995799\n").unwrap(),
            &HashMap::new(),
        );
        // 食 (2^19..2^20) is commoner than 識 (2^18..2^19), so 食咗 outweighs 識咗 although the essay lists neither word.
        assert_eq!(
            dictionary.entries[&("sik zo".to_owned(), "食咗".to_owned())],
            20
        );
        assert_eq!(
            dictionary.entries[&("sik zo".to_owned(), "識咗".to_owned())],
            19
        );
    }

    #[test]
    fn the_corpus_weighs_words_the_essay_lacks_on_the_essay_scale() {
        let characters = format!(
            "{HEADER}我\tngo5\n哋\tdei6\n地\tdei6\n點\tdim2\n解\tgaai2\n佢\tkeoi5\n咩\tme1\n"
        );
        let words = format!("{HEADER}我哋\tngo5 dei6\n我地\tngo5 dei6\n點解\tdim2 gaai2\n佢哋\tkeoi5 dei6\n咩哋\tme1 dei6\n");
        let essay = parse_essay("我\t900000\n哋\t1000000\n地\t800000\n點解\t480000\n我地\t55000\n佢\t500000\n咩\t300000\n").unwrap();
        // 點解 and 我地 are in both lists: their ratios are 480000/200 = 2400 and 55000/50 = 1100, and the lower median of the two is 1100.
        let corpus = crate::hkcancor::parse("點解\t200\n我地\t50\n我哋\t400\n佢哋\t300\n").unwrap();
        let dictionary = build(
            &parse_characters(&characters).unwrap(),
            &parse_words(&words).unwrap(),
            &essay,
            &corpus,
        );
        assert_eq!(dictionary.corpus_scale, 1100);
        let weight = |key: &str, text: &str| dictionary.entries[&(key.to_owned(), text.to_owned())];
        // The essay lists 我地 and 點解, so their essay counts stand.
        assert_eq!(weight("ngo dei", "我地"), 55000);
        assert_eq!(weight("dim gaai", "點解"), 480000);
        // 我哋 is missing from the essay; 400 corpus tokens at 1100 each put it ahead of 我地.
        assert_eq!(weight("ngo dei", "我哋"), 440000);
        assert_eq!(weight("keoi dei", "佢哋"), 330000);
        // 咩哋 is in neither list and keeps the fallback, 1 + log2(300000).
        assert_eq!(weight("me dei", "咩哋"), 19);
        assert_eq!(dictionary.corpus_words, 2);
    }

    #[test]
    fn a_thin_corpus_word_stays_below_the_essay_words_of_its_key() {
        let characters = format!(
            "{HEADER}物\tmat6\n證\tzing3\n証\tzing3\n人\tjan4\n印\tjan3\n唔\tm4\n止\tzi2\n只\tzi2\n知\tzi1\n"
        );
        let words = format!(
            "{HEADER}物證\tmat6 zing3\n物証\tmat6 zing3\n人證\tjan4 zing3\n印證\tjan3 zing3\n人証\tjan4 zing3\n唔止\tm4 zi2\n唔知\tm4 zi1\n"
        );
        // 唔只 is not in the words file; the essay adds it under m zi, and it is the key's only essay word besides 唔知.
        let essay = parse_essay(
            "物\t600000\n證\t300000\n証\t2000\n人\t900000\n印\t200000\n唔\t2000000\n止\t400000\n只\t500000\n知\t800000\n物證\t718\n人證\t580\n印證\t889\n唔知\t1518\n唔只\t5606\n點解\t480000\n",
        )
        .unwrap();
        let corpus = crate::hkcancor::parse("點解\t568\n物証\t2\n人証\t2\n唔止\t3\n").unwrap();
        let dictionary = build(
            &parse_characters(&characters).unwrap(),
            &parse_words(&words).unwrap(),
            &essay,
            &corpus,
        );
        assert_eq!(dictionary.corpus_scale, 845);
        let weight = |key: &str, text: &str| dictionary.entries[&(key.to_owned(), text.to_owned())];
        // Two tokens would weigh 1690, ahead of 物證; they are held one below it.
        assert_eq!(weight("mat zing", "物証"), 717);
        // jan zing has 人證 (580) and 印證 (889); a thin word stays below both.
        assert_eq!(weight("jan zing", "人証"), 579);
        // Three tokens reach the threshold and keep the corpus weight, which passes 唔知 but not 唔只, the essay word added under the same key.
        assert_eq!(weight("m zi", "唔止"), 2535);
        assert_eq!(weight("m zi", "唔只"), 5606);
        assert_eq!((dictionary.corpus_words, dictionary.corpus_capped), (3, 2));
    }

    #[test]
    fn a_thin_corpus_word_never_drops_below_its_fallback() {
        let characters = format!("{HEADER}噉\tgam2\n解\tgaai2\n禁\tgam3\n戒\tgaai3\n");
        let words = format!("{HEADER}噉解\tgam2 gaai2\n禁戒\tgam3 gaai3\n");
        // 點解 sets the scale to 845. 禁戒 weighs 3 in the essay, below 噉解's fallback of 1 + log2(1024) = 11, so 噉解 drops from 845 to its fallback and no further.
        let essay =
            parse_essay("噉\t1024\n解\t4096\n禁\t9000\n戒\t9000\n禁戒\t3\n點解\t845000\n").unwrap();
        let corpus = crate::hkcancor::parse("噉解\t1\n點解\t1000\n").unwrap();
        let dictionary = build(
            &parse_characters(&characters).unwrap(),
            &parse_words(&words).unwrap(),
            &essay,
            &corpus,
        );
        assert_eq!(
            dictionary.entries[&("gam gaai".to_owned(), "噉解".to_owned())],
            11
        );
        assert_eq!(dictionary.corpus_capped, 1);
    }

    #[test]
    fn without_shared_words_the_corpus_scale_is_one() {
        let essay = parse_essay("你\t10\n").unwrap();
        let corpus = crate::hkcancor::parse("我哋\t4\n").unwrap();
        assert_eq!(corpus_scale(&essay, &corpus), 1);
    }

    #[test]
    fn a_unit_character_keeps_its_two_syllables() {
        let characters = format!("{HEADER}兡\tbaak3 hak1\n一\tjat1\n");
        let dictionary = build(
            &parse_characters(&characters).unwrap(),
            &[],
            &parse_essay("一兡\t1200\n").unwrap(),
            &HashMap::new(),
        );
        assert_eq!(
            entries(&dictionary),
            [
                ("baak hak", "兡", 1),
                ("jat", "一", 1),
                ("jat baak hak", "一兡", 1200)
            ]
        );
    }

    #[test]
    fn rare_essay_words_are_left_out() {
        let characters = characters_source();
        let dictionary = build(
            &parse_characters(&characters).unwrap(),
            &[],
            &parse_essay("你好\t999\n").unwrap(),
            &HashMap::new(),
        );
        assert_eq!(dictionary.essay_words, 0);
    }

    #[test]
    fn the_inventory_holds_every_syllable_a_key_uses() {
        let dictionary = sample();
        let syllables: Vec<&str> = dictionary.syllables.iter().map(String::as_str).collect();
        // fe, fi, le and li come only from the words file, dei from 你哋.
        assert_eq!(
            syllables,
            ["dei", "dung", "fe", "fi", "gwong", "hou", "le", "li", "ne", "nei", "waa"]
        );
    }

    #[test]
    fn malformed_rows_name_their_file_and_line() {
        for (source, expected) in [
            (format!("{HEADER}你\n"), "chars.dict.yaml: line 10 is not"),
            (
                format!("{HEADER}你好\tnei5\n"),
                "line 10: \"你好\" is not one character",
            ),
            (
                format!("{HEADER}你\tnei\n"),
                "line 10: \"nei\" is not a toned",
            ),
            (
                format!("{HEADER}你\tNei5\n"),
                "line 10: \"Nei5\" is not a toned",
            ),
            (
                format!("{HEADER}你\tnei5\t3\n"),
                "\"3\" is not a percentage",
            ),
            (
                format!("{HEADER}你\tnei5\t101%\n"),
                "\"101%\" is not a percentage",
            ),
            ("你\tnei5\n".to_owned(), "no `...` line"),
        ] {
            let error = parse_characters(&source).unwrap_err().to_string();
            assert!(error.contains(expected), "{error}");
        }
        let error = parse_words(&format!("{HEADER}\n你好\tnei5 hou2\t3\n"))
            .unwrap_err()
            .to_string();
        assert!(error.contains("words.dict.yaml: line 11"), "{error}");
        let error = parse_words(&format!("{HEADER}你好\tnei5  hou2\n"))
            .unwrap_err()
            .to_string();
        assert!(error.contains("\"\" is not a toned"), "{error}");
        for essay in ["你好\n", "你好\t-1\n", "\t3\n", "你好\t3\t4\n"] {
            let error = parse_essay(essay).unwrap_err().to_string();
            assert!(error.contains("essay-cantonese.txt: line 1"), "{error}");
        }
    }

    #[test]
    fn only_the_licensed_files_are_read() {
        for excluded in ["maps", "phrase", "lettered"] {
            assert!(
                [CHARACTERS, WORDS, ESSAY, CORPUS]
                    .iter()
                    .all(|input| !input.contains(excluded)),
                "{excluded}"
            );
        }
        let lock = crate::sources::Lock::load(
            &Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("../../resources/dictionary-sources.lock.json"),
        )
        .unwrap();
        assert_eq!(lock.references[REFERENCE].commit.len(), 40);
        for input in [CHARACTERS, WORDS, ESSAY] {
            assert_eq!(
                crate::sources::upstream_reference(input),
                Some(REFERENCE),
                "{input}"
            );
        }
        assert_eq!(
            crate::sources::upstream_reference(CORPUS),
            Some(crate::hkcancor::REFERENCE)
        );
        assert!(!lock
            .files
            .iter()
            .any(|file| file.path.starts_with("sources/cantonese/")));
    }

    fn written(dictionary: &Dictionary) -> (tempfile::TempDir, std::path::PathBuf) {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join(DATABASE);
        write(
            dictionary,
            &path,
            "259f0e48bba840c3a2e0d117539e96937f3d89bc",
        )
        .unwrap();
        (dir, path)
    }

    #[test]
    fn the_engine_reads_what_is_written_and_the_bytes_repeat() {
        let dictionary = sample();
        let (_dir, path) = written(&dictionary);
        let engine = language_dictionary::open_read_only(&path).unwrap();
        let texts: Vec<String> = engine
            .lookup("nei", 10)
            .unwrap()
            .into_iter()
            .map(|entry| entry.text)
            .collect();
        assert_eq!(texts, ["你", "呢", "妳"]);
        assert!(engine.has_syllable("fi").unwrap());
        assert_eq!(
            engine
                .metadata(language_dictionary::METADATA_SOURCE_COMMIT)
                .unwrap()
                .as_deref(),
            Some("259f0e48bba840c3a2e0d117539e96937f3d89bc")
        );
        assert_eq!(
            engine
                .metadata(language_dictionary::METADATA_LICENSE)
                .unwrap()
                .as_deref(),
            Some(LICENSE)
        );
        let first = std::fs::read(&path).unwrap();
        // Writing again over the earlier file gives the same bytes.
        write(
            &dictionary,
            &path,
            "259f0e48bba840c3a2e0d117539e96937f3d89bc",
        )
        .unwrap();
        assert_eq!(std::fs::read(&path).unwrap(), first);
    }

    #[test]
    fn verify_enforces_the_floors_and_the_expected_entries() {
        let (_dir, path) = written(&sample());
        let floors = Floors {
            syllables: 11,
            characters: 9,
            words: 4,
        };
        assert_eq!(
            verify(&path, floors).unwrap(),
            Counts {
                syllables: 11,
                characters: 9,
                words: 4
            }
        );
        for (below, what) in [
            (
                Floors {
                    syllables: 12,
                    ..floors
                },
                "11 syllables, below the floor of 12",
            ),
            (
                Floors {
                    characters: 10,
                    ..floors
                },
                "9 character entries, below the floor of 10",
            ),
            (
                Floors { words: 5, ..floors },
                "4 word entries, below the floor of 5",
            ),
        ] {
            let error = verify(&path, below).unwrap_err().to_string();
            assert!(error.contains(what), "{error}");
        }
        let error = verify(&path, FLOORS).unwrap_err().to_string();
        assert!(error.contains("below the floor"), "{error}");

        // Without the essay, 你好 is missing from nei hou.
        let characters = characters_source();
        let words = words_source();
        let (_dir, path) = written(&build(
            &parse_characters(&characters).unwrap(),
            &parse_words(&words).unwrap(),
            &HashMap::new(),
            &HashMap::new(),
        ));
        let error = verify(
            &path,
            Floors {
                syllables: 0,
                characters: 0,
                words: 0,
            },
        )
        .unwrap_err()
        .to_string();
        assert!(error.contains("without 你好"), "{error}");
    }
}
