//! The Chinese administrative divisions `@` mode can offer after the user's own list: provinces, cities, and counties and districts, from modood/Administrative-divisions-of-China (WTFPL) at commit c49d495b40ac73eb1a66f6eeae5f8fd10696f035 (data of 2025-12-27), the pin `resources/dictionary-sources.lock.json` holds under `places/`.
//!
//! `places.tsv` is generated by `msime-dict-build places` and embedded, so the table needs no download and no file on disk. Each line is `name<TAB>key<TAB>parent`: the key is the pinyin `'`-joined as a mention key is, the parent is the province of a city, or the city (the province, for a district of a municipality) of a county or district, and empty for a province. Lines come larger divisions first and each name occurs once.

use std::collections::HashMap;
use std::sync::OnceLock;

const TABLE: &str = include_str!("places.tsv");

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Place {
    pub name: &'static str,
    pub key: &'static str,
    pub parent: &'static str,
}

pub struct Places {
    pub places: Vec<Place>,
    /// The key without its apostrophes and the first letter of each syllable, per place, precomputed because every key in `@` mode scans the whole table.
    pub spellings: Vec<[String; 2]>,
    parents: HashMap<&'static str, &'static str>,
}

impl Places {
    fn parse(table: &'static str) -> Self {
        let mut places = Vec::with_capacity(table.lines().count());
        for line in table.lines() {
            let mut fields = line.split('\t');
            if let (Some(name), Some(key), Some(parent), None) =
                (fields.next(), fields.next(), fields.next(), fields.next())
            {
                places.push(Place { name, key, parent });
            }
        }
        let spellings = places
            .iter()
            .map(|place| {
                [
                    place.key.replace('\'', ""),
                    place
                        .key
                        .split('\'')
                        .filter_map(|syllable| syllable.chars().next())
                        .collect(),
                ]
            })
            .collect();
        let parents = places
            .iter()
            .map(|place| (place.name, place.parent))
            .collect();
        Self {
            places,
            spellings,
            parents,
        }
    }

    /// The division a place belongs to, empty for a province, `None` when the text is not a place.
    pub fn parent(&self, name: &str) -> Option<&'static str> {
        self.parents.get(name).copied()
    }
}

/// The embedded table, parsed on first use.
pub fn places() -> &'static Places {
    static PLACES: OnceLock<Places> = OnceLock::new();
    PLACES.get_or_init(|| Places::parse(TABLE))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_embedded_table_is_well_formed() {
        let table = places();
        assert_eq!(table.places.len(), TABLE.lines().count());
        assert_eq!(table.places.capacity(), TABLE.lines().count());
        assert!(table.places.len() > 3000);
        assert_eq!(table.parents.len(), table.places.len());
        for place in &table.places {
            assert!(!place.name.trim().is_empty(), "{place:?}");
            assert!(
                place.key.split('\'').all(|syllable| !syllable.is_empty()
                    && syllable.bytes().all(|byte| byte.is_ascii_lowercase())),
                "{place:?}"
            );
            assert!(
                place.parent.is_empty() || table.parent(place.parent).is_some(),
                "{place:?}"
            );
        }
    }

    #[test]
    fn places_carry_their_reading_and_parent() {
        let table = places();
        let find = |name: &str| {
            *table
                .places
                .iter()
                .find(|place| place.name == name)
                .unwrap()
        };
        assert_eq!(
            find("重庆市"),
            Place {
                name: "重庆市",
                key: "chong'qing'shi",
                parent: ""
            }
        );
        assert_eq!(find("六安市").key, "lu'an'shi");
        assert_eq!(find("厦门市").key, "xia'men'shi");
        assert_eq!(table.parent("深圳市"), Some("广东省"));
        assert_eq!(table.parent("朝阳区"), Some("北京市"));
        assert_eq!(table.parent("张三"), None);
        assert_eq!(table.places[0].name, "北京市");
    }
}
